/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        lato: ['Lato', 'sans-serif'],
        'open-sans': ['Open Sans', 'sans-serif'],
      },
      colors: {
        'sidebar-text': '#e4f1ff',
        'light-blue-bg': '#f8f9fd',
        'screen-bg': '#f5f5f5',
        white: '#fff',
        'disabled-grey': '#888',
        'light-grey': '#b1aeae',
        'tertiary-text': '#626262',
        'tertiary-hover': '#4b4b4b',
        'tertiary-hover-btn': '#494949',
        'clue-text': '#333338',
        'tertiary-active': '#2d2d2d',
        'tertiary-active-hover': '#333',
        'sidebar-bg': '#1e252f',
        'text-black': '#071933',
        'top-menu-dark': '#0a1321',
        black: '#000',
        'primary-blue': '#1e70eb',
        'active-blue': '#4285f4',
        'disabled-blue': '#2a4875',
        'light-blue': '#2e57db',
        'card-background': '#2f4865',
        'normal-ui': '#91a2b6',
        'hover-blue': '#a1caff',
        'card-border': '#bcd7ff',
        'input-normal': '#d2e4ff',
        'input-normal-state': '#e8f2ff',
        red: '#fa2727',
        yellow: '#ffb800',
        purple: '#9747ff',
        'wave-blue': '#45d0ee',
        'disabled-gray': '#888',
        'hover-gray': '#788aa0',
        'light-gray': '#ccc',
        orange: '#f16600',
        'light-green': '#84e78d',
        'dark-green': '#14B541',
        'color-designer': '#94c748',
        'color-front-end': '#f5cd47',
        'color-back-end': '#9f8fef',
        'color-qa': '#f87168',
        'color-full-stack': '#fea362',
        'color-pm': '#579dff',
        'blue-hover': '#f0f2fb',
      },
    },
    screens: {
      md: '1366px',
      lg: '1920px',
      xl: '2560px',
    },
    backgroundPosition: {
      'custom-position': 'center top 30px',
    },
  },
  plugins: [],
};
