export const users = [
  {
    id: 1,
    city: 'Lviv',
    country: 'Ukraine',
    discord: 'user1#1234',
    email: 'nik.smort1@gmail.com',
    firstName: 'Nik',
    lastName: 'Spartan',
    linkedin: 'https://linkedin.com/in/nik1',
    phone: '+380 565 454 111',
    specialization: 'Frontend',
    status: true,
  },
  {
    id: 2,
    city: 'Kyiv',
    country: 'Ukraine',
    discord: 'user2#5678',
    email: 'kat.smith@gmail.com',
    firstName: 'Kat',
    lastName: 'Smith',
    linkedin: 'https://linkedin.com/in/kat2',
    phone: '+380 565 454 222',
    specialization: 'Backend',
    status: false,
  },
  {
    id: 3,
    city: 'Odessa',
    country: 'Ukraine',
    discord: 'user3#9101',
    email: 'john.doe@gmail.com',
    firstName: 'John',
    lastName: 'Doe',
    linkedin: 'https://linkedin.com/in/john3',
    phone: '+380 565 454 333',
    specialization: 'Fullstack',
    status: true,
  },
  {
    id: 4,
    city: 'Kharkiv',
    country: 'Ukraine',
    discord: 'user4#1121',
    email: 'anna.kovalenko@gmail.com',
    firstName: 'Anna',
    lastName: 'Kovalenko',
    linkedin: 'https://linkedin.com/in/anna4',
    phone: '+380 565 454 444',
    specialization: 'DevOps',
    status: null,
  },
  {
    id: 5,
    city: 'Dnipro',
    country: 'Ukraine',
    discord: 'user5#3141',
    email: 'peter.petrov@gmail.com',
    firstName: 'Peter',
    lastName: 'Petrol',
    linkedin: 'https://linkedin.com/in/peter5',
    phone: '+380 565 454 555',
    specialization: 'Frontend',
    status: false,
  },
];
