export const projects = [
  {
    id: 1,
    label: 'В розробці',
    title: 'Лендінг для фінансів',
    tags: [
      { id: 1, label: 'Frontend', number: 5, all: 5 },
      { id: 2, label: 'Backend', number: 3, all: 3 },
      { id: 3, label: 'QA', number: 2, all: 2 },
      { id: 4, label: 'Project', number: 1, all: 1 },
      { id: 5, label: 'Design', number: 2, all: 2 },
    ],
    points: 6,
    teamStart: '2023-01-10',
    projectStart: '2023-02-15',
  },
  {
    id: 2,
    label: 'Формується команда',
    title: 'Мобільний додаток для спорту',
    tags: [
      { id: 1, label: 'Frontend', number: 2, all: 4 },
      { id: 2, label: 'Backend', number: 1, all: 3 },
      { id: 3, label: 'QA', number: 0, all: 2 },
      { id: 4, label: 'Project', number: 1, all: 1 },
      { id: 5, label: 'Design', number: 1, all: 2 },
    ],
    points: 8,
    teamStart: '2023-03-05',
    projectStart: '2023-04-20',
  },
  {
    id: 3,
    label: 'Завершені',
    title: 'CRM для маркетингу',
    tags: [
      { id: 1, label: 'Frontend', number: 4, all: 4 },
      { id: 2, label: 'Backend', number: 3, all: 3 },
      { id: 3, label: 'QA', number: 2, all: 2 },
      { id: 4, label: 'Project', number: 1, all: 1 },
      { id: 5, label: 'Design', number: 1, all: 1 },
    ],
    points: 10,
    teamStart: '2022-11-01',
    projectStart: '2022-12-10',
  },
  {
    id: 4,
    label: 'В розробці',
    title: 'Електронна комерція платформа',
    tags: [
      { id: 1, label: 'Frontend', number: 5, all: 5 },
      { id: 2, label: 'Backend', number: 4, all: 4 },
      { id: 3, label: 'QA', number: 3, all: 3 },
      { id: 4, label: 'Project', number: 1, all: 1 },
      { id: 5, label: 'Design', number: 2, all: 2 },
    ],
    points: 7,
    teamStart: '2023-05-12',
    projectStart: '2023-06-15',
  },
  {
    id: 5,
    label: 'Формується команда',
    title: 'Соціальна мережа',
    tags: [
      { id: 1, label: 'Frontend', number: 1, all: 6 },
      { id: 2, label: 'Backend', number: 2, all: 5 },
      { id: 3, label: 'QA', number: 0, all: 3 },
      { id: 4, label: 'Project', number: 1, all: 1 },
      { id: 5, label: 'Design', number: 1, all: 2 },
    ],
    points: 9,
    teamStart: '2023-07-01',
    projectStart: '2023-08-10',
  },
  {
    id: 6,
    label: 'Завершені',
    title: 'Інвентарна менеджмент система',
    tags: [
      { id: 1, label: 'Frontend', number: 3, all: 3 },
      { id: 2, label: 'Backend', number: 3, all: 3 },
      { id: 3, label: 'QA', number: 2, all: 2 },
      { id: 4, label: 'Project', number: 1, all: 1 },
      { id: 5, label: 'Design', number: 1, all: 1 },
    ],
    points: 8,
    teamStart: '2022-09-15',
    projectStart: '2022-10-20',
  },
  {
    id: 7,
    label: 'В розробці',
    title: 'Доставка їжі додаток',
    tags: [
      { id: 1, label: 'Frontend', number: 4, all: 4 },
      { id: 2, label: 'Backend', number: 3, all: 3 },
      { id: 3, label: 'QA', number: 1, all: 2 },
      { id: 4, label: 'Project', number: 1, all: 1 },
      { id: 5, label: 'Design', number: 1, all: 2 },
    ],
    points: 7,
    teamStart: '2023-02-01',
    projectStart: '2023-03-15',
  },
  {
    id: 8,
    label: 'Формується команда',
    title: 'Медична платформа',
    tags: [
      { id: 1, label: 'Frontend', number: 2, all: 5 },
      { id: 2, label: 'Backend', number: 1, all: 4 },
      { id: 3, label: 'QA', number: 0, all: 3 },
      { id: 4, label: 'Project', number: 1, all: 1 },
      { id: 5, label: 'Design', number: 1, all: 2 },
    ],
    points: 6,
    teamStart: '2023-04-10',
    projectStart: '2023-05-20',
  },
];
